# TCL File Generated by Component Editor 17.1
# Sun Nov 18 14:25:50 EST 2018
# DO NOT MODIFY


# 
# regfile "regfile" v1.0
#  2018.11.18.14:25:50
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module regfile
# 
set_module_property DESCRIPTION ""
set_module_property NAME regfile
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME regfile
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL regfile
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file regfile.v VERILOG PATH ../../device/hardware-logic-analyzer/regfile.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_n
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 6
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1


# 
# connection point registers
# 
add_interface registers conduit end
set_interface_property registers associatedClock clock
set_interface_property registers associatedReset reset_n
set_interface_property registers ENABLED true
set_interface_property registers EXPORT_OF ""
set_interface_property registers PORT_NAME_MAP ""
set_interface_property registers CMSIS_SVD_VARIABLES ""
set_interface_property registers SVD_ADDRESS_GROUP ""

add_interface_port registers reg_0 reg_0 Output 32
add_interface_port registers reg_1 reg_1 Output 32
add_interface_port registers reg_2 reg_2 Output 32
add_interface_port registers reg_3 reg_3 Output 32
add_interface_port registers reg_4 reg_4 Output 32
add_interface_port registers reg_5 reg_5 Output 32
add_interface_port registers reg_6 reg_6 Output 32
add_interface_port registers reg_7 reg_7 Output 32
add_interface_port registers reg_8 reg_8 Output 32
add_interface_port registers reg_9 reg_9 Output 32
add_interface_port registers reg_10 reg_10 Output 32
add_interface_port registers reg_11 reg_11 Output 32
add_interface_port registers reg_12 reg_12 Output 32
add_interface_port registers reg_13 reg_13 Output 32
add_interface_port registers reg_14 reg_14 Output 32
add_interface_port registers reg_15 reg_15 Output 32
add_interface_port registers reg_16 reg_16 Output 32
add_interface_port registers reg_17 reg_17 Output 32
add_interface_port registers reg_18 reg_18 Output 32
add_interface_port registers reg_19 reg_19 Output 32
add_interface_port registers reg_20 reg_20 Output 32
add_interface_port registers reg_21 reg_21 Output 32
add_interface_port registers reg_22 reg_22 Output 32
add_interface_port registers reg_23 reg_23 Output 32
add_interface_port registers reg_24 reg_24 Output 32
add_interface_port registers reg_25 reg_25 Output 32
add_interface_port registers reg_26 reg_26 Output 32
add_interface_port registers reg_27 reg_27 Output 32
add_interface_port registers reg_28 reg_28 Output 32
add_interface_port registers reg_29 reg_29 Output 32
add_interface_port registers reg_30 reg_30 Output 32
add_interface_port registers reg_31 reg_31 Output 32
add_interface_port registers reg_32 reg_32 Input 32
add_interface_port registers reg_33 reg_33 Input 32
add_interface_port registers reg_34 reg_34 Input 32
add_interface_port registers reg_35 reg_35 Input 32
add_interface_port registers reg_36 reg_36 Input 32
add_interface_port registers reg_37 reg_37 Input 32
add_interface_port registers reg_38 reg_38 Input 32
add_interface_port registers reg_39 reg_39 Input 32
add_interface_port registers reg_40 reg_40 Input 32
add_interface_port registers reg_41 reg_41 Input 32
add_interface_port registers reg_42 reg_42 Input 32
add_interface_port registers reg_43 reg_43 Input 32
add_interface_port registers reg_44 reg_44 Input 32
add_interface_port registers reg_45 reg_45 Input 32
add_interface_port registers reg_46 reg_46 Input 32
add_interface_port registers reg_47 reg_47 Input 32
add_interface_port registers reg_48 reg_48 Input 32
add_interface_port registers reg_49 reg_49 Input 32
add_interface_port registers reg_50 reg_50 Input 32
add_interface_port registers reg_51 reg_51 Input 32
add_interface_port registers reg_52 reg_52 Input 32
add_interface_port registers reg_53 reg_53 Input 32
add_interface_port registers reg_54 reg_54 Input 32
add_interface_port registers reg_55 reg_55 Input 32
add_interface_port registers reg_56 reg_56 Input 32
add_interface_port registers reg_57 reg_57 Input 32
add_interface_port registers reg_58 reg_58 Input 32
add_interface_port registers reg_59 reg_59 Input 32
add_interface_port registers reg_60 reg_60 Input 32
add_interface_port registers reg_61 reg_61 Input 32
add_interface_port registers reg_62 reg_62 Input 32
add_interface_port registers reg_63 reg_63 Input 32

